spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wasalliya_qa_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate #
    show-sql: true